# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patrick\Documents\maya\2014-x64\scripts\FluidExplorerPlugin\ui\Resources\DetailsViewUI.ui'
#
# Created: Tue Aug 09 11:30:47 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 625)
        self.label_projectName = QtGui.QLabel(Form)
        self.label_projectName.setGeometry(QtCore.QRect(20, 49, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_projectName.setFont(font)
        self.label_projectName.setObjectName("label_projectName")
        self.lineEdit_projectName = QtGui.QLineEdit(Form)
        self.lineEdit_projectName.setGeometry(QtCore.QRect(20, 71, 301, 20))
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.pushButton_applyCache = QtGui.QPushButton(Form)
        self.pushButton_applyCache.setGeometry(QtCore.QRect(230, 285, 91, 23))
        self.pushButton_applyCache.setObjectName("pushButton_applyCache")
        self.comboBox_simulations = QtGui.QComboBox(Form)
        self.comboBox_simulations.setGeometry(QtCore.QRect(20, 286, 191, 21))
        self.comboBox_simulations.setObjectName("comboBox_simulations")
        self.line_1 = QtGui.QFrame(Form)
        self.line_1.setGeometry(QtCore.QRect(20, 29, 300, 25))
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.label_detailsView = QtGui.QLabel(Form)
        self.label_detailsView.setGeometry(QtCore.QRect(20, 9, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_detailsView.setFont(font)
        self.label_detailsView.setStyleSheet("")
        self.label_detailsView.setObjectName("label_detailsView")
        self.checkBox_showPreview = QtGui.QCheckBox(Form)
        self.checkBox_showPreview.setGeometry(QtCore.QRect(20, 257, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_showPreview.setFont(font)
        self.checkBox_showPreview.setObjectName("checkBox_showPreview")
        self.lineEdit_projectPath = QtGui.QLineEdit(Form)
        self.lineEdit_projectPath.setGeometry(QtCore.QRect(20, 121, 300, 20))
        self.lineEdit_projectPath.setObjectName("lineEdit_projectPath")
        self.label_projectPath = QtGui.QLabel(Form)
        self.label_projectPath.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_projectPath.setFont(font)
        self.label_projectPath.setObjectName("label_projectPath")
        self.label_fluidContainer = QtGui.QLabel(Form)
        self.label_fluidContainer.setGeometry(QtCore.QRect(20, 149, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fluidContainer.setFont(font)
        self.label_fluidContainer.setObjectName("label_fluidContainer")
        self.lineEdit_fluidContainer = QtGui.QLineEdit(Form)
        self.lineEdit_fluidContainer.setGeometry(QtCore.QRect(20, 170, 121, 20))
        self.lineEdit_fluidContainer.setObjectName("lineEdit_fluidContainer")
        self.lineEdit_startTime = QtGui.QLineEdit(Form)
        self.lineEdit_startTime.setGeometry(QtCore.QRect(160, 170, 71, 20))
        self.lineEdit_startTime.setObjectName("lineEdit_startTime")
        self.label_startTime = QtGui.QLabel(Form)
        self.label_startTime.setGeometry(QtCore.QRect(160, 149, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_startTime.setFont(font)
        self.label_startTime.setObjectName("label_startTime")
        self.label_endTime = QtGui.QLabel(Form)
        self.label_endTime.setGeometry(QtCore.QRect(250, 149, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_endTime.setFont(font)
        self.label_endTime.setObjectName("label_endTime")
        self.lineEdit_endTime = QtGui.QLineEdit(Form)
        self.lineEdit_endTime.setGeometry(QtCore.QRect(250, 169, 70, 20))
        self.lineEdit_endTime.setObjectName("lineEdit_endTime")
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 229, 300, 25))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_loadSimulation = QtGui.QLabel(Form)
        self.label_loadSimulation.setGeometry(QtCore.QRect(20, 209, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_loadSimulation.setFont(font)
        self.label_loadSimulation.setStyleSheet("")
        self.label_loadSimulation.setObjectName("label_loadSimulation")
        self.label_preview = QtGui.QLabel(Form)
        self.label_preview.setGeometry(QtCore.QRect(20, 359, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_preview.setFont(font)
        self.label_preview.setStyleSheet("QLabel\n"
"{\n"
"qproperty-alignment: AlignCenter;\n"
"}")
        self.label_preview.setObjectName("label_preview")
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(20, 379, 300, 25))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_moviePreview = QtGui.QLabel(Form)
        self.label_moviePreview.setGeometry(QtCore.QRect(20, 407, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_moviePreview.setFont(font)
        self.label_moviePreview.setAutoFillBackground(False)
        self.label_moviePreview.setStyleSheet("QLabel { background-color : green; color : black; };")
        self.label_moviePreview.setText("")
        self.label_moviePreview.setObjectName("label_moviePreview")
        self.pushButton_exploreSimulations = QtGui.QPushButton(Form)
        self.pushButton_exploreSimulations.setGeometry(QtCore.QRect(20, 320, 301, 23))
        self.pushButton_exploreSimulations.setText("Explore Simulations  ...")
        self.pushButton_exploreSimulations.setObjectName("pushButton_exploreSimulations")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_projectName.setText(QtGui.QApplication.translate("Form", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_applyCache.setText(QtGui.QApplication.translate("Form", "Apply Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_detailsView.setText(QtGui.QApplication.translate("Form", "Project Details", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_showPreview.setText(QtGui.QApplication.translate("Form", "Show Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_projectPath.setText(QtGui.QApplication.translate("Form", "Project Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fluidContainer.setText(QtGui.QApplication.translate("Form", "Fluid Container", None, QtGui.QApplication.UnicodeUTF8))
        self.label_startTime.setText(QtGui.QApplication.translate("Form", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_endTime.setText(QtGui.QApplication.translate("Form", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loadSimulation.setText(QtGui.QApplication.translate("Form", "Load Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_preview.setText(QtGui.QApplication.translate("Form", "Preview", None, QtGui.QApplication.UnicodeUTF8))

